// Cohorts
export const SET_COHORTS_LIST = 'SET_COHORTS_LIST'
export const SET_CURRENT_COHORT = 'SET_CURRENT_COHORT'

// Users
export const SET_USERS_LIST = 'SET_USERS_LIST'
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA'
export const SET_LOGGED_USER_DATA = 'SET_LOGGED_USER_DATA'
export const REMOVE_LOGGED_USER_DATA = 'REMOVE_LOGGED_USER_DATA'

// Posts
export const SET_POSTS_LIST = 'SET_POSTS_LIST'
